### ISSUE TITLE
Feature - User can view a list of other user profiles

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other user profiles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to scroll through a list of user profiles

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/95939062/171084812-67d230bf-e99e-427c-ac74-a3afdfe699fb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include imported db from 
- [x] Update `data.sql` to include some dummy data for testing

### ☁️ Server

- [x] Update `server/index.js` to handle get request from client, and then send a db request for relevant info
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to create the header and navbar
- [x] create a component to create the character profile cards
- [x] implement header + logo
- [x] create profile cards for each individual profile
- [x] use row , wrap to display cards
- [x] give entire card a onclick function call (brings up profile)
- [x] create a fetch function for clientside server requests

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
