### ISSUE TITLE
Feature: User can login to an account

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login to their account
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user types in their username and password, if correct, are redirected to the home page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="340" alt="Screen Shot 2022-05-31 at 10 41 26 AM" src="https://user-images.githubusercontent.com/95939062/171246604-38105de7-cf1b-453e-b0bf-0118f67e7a3b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a path for retrieving the user information
  - [x] needs to include authentication via tokens
  - [x] needs to check if the password is the same as the hashedpassword stored in the server
    - [x] use argon2 to verify
  - [x] have authorization middleware for all processes that need authorization  (x-token)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update account creation component to include login component
- [x] update account creation component to store token in local storage
  - [x] add to the componentDidMount method a way to check storage for token 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
