### ISSUE TITLE
Feature: User can view profiles of other users

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view detailed profile of other users
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to select a profile from the user list and pull up a more detailed profile list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/95939062/171240805-ce00db3b-e33a-4d35-a351-b17ad35737d0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a get request for specific profiles according to selected userId (where clause)
  - [x] use condition to potentially insert an empty string/where clause? reuse get 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for hash routing
  - [x] routes to profile when user card is clicked 
- [x] create front end for profile view
- [x] remove click listener to make way for hash routing
- [x] create new button to open up chat (new hash route)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
