### ISSUE TITLE
Feature: User can send a message to another user

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a message to another user
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user clicks on start a new chat, brings up a chat screen, can type in messages and see them post in real time.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/95939062/171242180-15559861-922d-4be7-8be2-cf6ebc9c976f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ☁️ Server

- [x] Update `server/index.js` to send a insert query to the db when a message is sent
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create a component to display the chatroom
- [x] Create a component to send the submitted messages
  - [x] add fetch function with a post method
  - [x] add onChange to track the changes in the input box
 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
