### ISSUE TITLE
Feature: User can user can view messages in chat

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can check messages from other users

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the messages list, there's a list of users that have messaged. User can click on the list and check their chat with that user.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/95939062/171242964-be5b9db3-a7cc-4b4b-a5df-3baed64cd02f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include paths for chat-list and message get requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] update chat-room component, able to view received messages AND sent messages
  - [x] list messages from each side
    - [x] messages should be in chronological order, older messages at top, newer messages at bottom
  - [x] update chat box to scroll down (set y dimension at certain point) 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
