### ISSUE TITLE
Feature: User can create a new account

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can create an account and fill out profile info
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user is able to select a sign up button, fill in a profile and username. They hit next, which then brings up another view,
where they can enter their name, upload a picture, select tags
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/95939062/171247400-56adc511-ee3b-454c-b0f5-c131fe1264de.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include firstName, gender, age, city/location for user, indoor/outdoor, belayer for tags
- [x] Update `data.sql` to include values for those included tags, may not be necessarily used/displayed for now.

### ☁️ Server

- [x] Update `server/index.js` to include a path for posting user data during after an account has been created
- [x] update a few file paths to account for some changes in the schema
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to handle account creation 
  - [x] add selectable tags
- [x] create another hidden view to create two-part sign up, one for the rest of profile creation.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
